fixtures:
  symlinks:
    nginx: "#{source_dir}"
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
